### ISSUE TITLE
[Urgent] Exception while load AdaptLLM/medicine-chat, variant of llama

### ISSUE THREAD

**Issue by jchauhan** [erfanzar/EasyDeL#114]
**Describe the bug**
The following exception is generated as a result of loading medicine-llama, fine tuned on LLama model (AdaptLLM/medicine-chat)

Error at the end loading
```
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/neo/research/belie/run_medicine_llama_jax.py", line 179, in <module>
    run(main)
  File "/home/neo/research/belie/.venv/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/home/neo/research/belie/.venv/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/home/neo/research/belie/run_medicine_llama_jax.py", line 147, in main
    server = JAXServerC.from_torch_pretrained(
  File "/home/neo/research/belie/.venv/lib/python3.10/site-packages/EasyDel/serve/jax_serve.py", line 430, in from_torch_pretrained
    return cls.from_parameters(
  File "/home/neo/research/belie/.venv/lib/python3.10/site-packages/EasyDel/serve/jax_serve.py", line 497, in from_parameters
    params[key] = shard_fns[key](params[key])
  File "/home/neo/research/belie/.venv/lib/python3.10/site-packages/fjformer/partition_utils/mesh_utils.py", line 50, in shard_fn
    return jax_shard_function(tensor).block_until_ready()
ValueError: One of pjit outputs was given the sharding of NamedSharding(mesh=Mesh('dp': 1, 'fsdp': 8, 'tp': 1, 'sp': 1), spec=PartitionSpec(('fsdp', 'sp'),)), which implies that the global size of its dimension 0 should be divisible by 8, but it is equal to 32001 (full shape: (32001, 4096))
I0228 05:42:31.892486 140176908027648 _client.py:1027] HTTP Request: POST https://api.gradio.app/gradio-initiated-analytics/ "HTTP/1.1 200 OK"
```

**To Reproduce**

Here is the Sample code

```
import json
from typing import List, Union

from absl.app import run
from absl import flags
from EasyDel import JAXServer, JAXServerConfig
import jax
from fjformer import get_dtype
from EasyDel.serve.prompters import GemmaPrompter, Llama2Prompter, OpenChatPrompter, Qwen2Prompter
from EasyDel.serve.prompters.base_prompter import BasePrompter

FLAGS = flags.FLAGS
flags.DEFINE_enum(
    "prompter_type",
    enum_values=("gemma", "llama", "openchat", "qwen2"),
    help="Prompter to be used to prompt the model",
    default="llama"
)
flags.DEFINE_string(
    "pretrained_model_name_or_path",
    default="AdaptLLM/medicine-chat",
    help="The pretrained model path in huggingface.co/models"
)
flags.DEFINE_integer(
    "max_compile_tokens",
    default=256,
    help="Maximum number of compiled tokens"
)

flags.DEFINE_integer(
    "max_new_tokens_ratio",
    default=20,
    help="max new tokens ratio to be multiplied for max_compile_tokens for max_new_tokens"
)

flags.DEFINE_integer(
    "max_sequence_length",
    default=2048,
    help="max sequence length to be used in the model"
)

flags.DEFINE_enum(
    "dtype",
    enum_values=(
        "bf16",
        "fp16",
        "fp32"
    ),
    default="bf16",
    help="The data type of the model"
)

flags.DEFINE_list(
    "sharding_axis_dims",
    default=[1, 1, 1, -1],
    help="Sharding Axis dimensions for the model"
)

flags.DEFINE_bool(
    "use_sharded_kv_caching",
    default=False,
    help="whether to use sharded kv for Large Sequence model up to 1M"
)

flags.DEFINE_bool(
    "scan_ring_attention",
    default=True,
    help="whether to scan ring attention for Large Sequence model up to 1M (works with attn_mechanism='ring')"
)

flags.DEFINE_bool(
    "use_scan_mlp",
    default=True,
    help="whether to scan MLP or FFN Layers for Large Sequence model up to 1M"
)

flags.DEFINE_enum(
    "attn_mechanism",
    enum_values=["normal", "flash", "ring", "splash"],
    default="normal",
    help="The attention mechanism to be used in the model"
)

flags.DEFINE_integer(
    "block_k",
    default=128,
    help="the number of chunks for key block in attention (Works with flash, splash, ring Attention mechanism)"
)

flags.DEFINE_integer(
    "block_q",
    default=128,
    help="the number of chunks for query block in attention (Works with flash, splash, ring Attention mechanism)"
)

flags.DEFINE_bool(
    "share_gradio",
    default=True,
    help="whether to share gradio app"
)

flags.DEFINE_string(
    "gradio_root_path",
    default="",
    help="Root Path to host Geadio Server"
)


def main(argv):
    server_config = JAXServerConfig(
        max_sequence_length=FLAGS.max_sequence_length,
        max_compile_tokens=FLAGS.max_compile_tokens,
        max_new_tokens=FLAGS.max_compile_tokens * FLAGS.max_new_tokens_ratio,
        dtype=FLAGS.dtype
    )
    prompters = {
        "gemma": GemmaPrompter(),
        "llama": Llama2Prompter(),
        "openchat": OpenChatPrompter(),
        "qwen2": Qwen2Prompter()
    }
    prompter: BasePrompter = prompters[FLAGS.prompter_type]

    FLAGS.sharding_axis_dims = tuple([int(s) for s in FLAGS.sharding_axis_dims])


    class JAXServerC(JAXServer):
        @staticmethod
        def format_chat(history: List[List[str]], prompt: str, system: Union[str, None]) -> str:
            return prompter.format_message(
                history=[],
                prompt=prompt,
                system_message=system,
                prefix=None
            )


        @staticmethod
        def format_instruct(system: str, instruction: str) -> str:
            return prompter.format_message(
                prefix=None,
                system_message=system,
                prompt=instruction,
                history=[]
            )

    server = JAXServerC.from_torch_pretrained(
        server_config=server_config,
        pretrained_model_name_or_path=FLAGS.pretrained_model_name_or_path,
        device=jax.devices('cpu')[0],
        dtype=get_dtype(dtype=FLAGS.dtype),
        param_dtype=get_dtype(dtype=FLAGS.dtype),
        precision=jax.lax.Precision("fastest"),
        sharding_axis_dims=FLAGS.sharding_axis_dims,
        sharding_axis_names=("dp", "fsdp", "tp", "sp"),
        input_shape=(1, server_config.max_sequence_length),
        model_config_kwargs=dict(
            fully_sharded_data_parallel=True,
            attn_mechanism=FLAGS.attn_mechanism,
            scan_mlp_chunk_size=FLAGS.max_compile_tokens,
            use_scan_mlp=FLAGS.use_scan_mlp,
            scan_ring_attention=FLAGS.scan_ring_attention,
            block_k=FLAGS.block_k,
            block_q=FLAGS.block_q,
            use_sharded_kv_caching=FLAGS.use_sharded_kv_caching
        )
    )

    server.gradio_inference().launch(
        root_path=FLAGS.gradio_root_path
        server_name="0.0.0.0",
        server_port=7680,
        show_api=True,
        share=FLAGS.share_gradio
    )


if __name__ == "__main__":
    run(main)


```

**Comment by erfanzar** [comment]
For custom models with custom sizes you have to change partition spec and partition rules for the model i recommend reading jax.sharding documentation but you have to replace partition spec of wte with tp,(fsdp,sp)

**Comment by jchauhan** [comment]
Thanks a lot. Much Appreciated!!

For this case, can you suggest what will these be?

In the main time, let me read the docs

How does Huggingface handle it automatically? Ideally, a library should take care of these parameters if possible from the Model Specs.

**Comment by erfanzar** [comment]
Actually huggingface wont do anything and all of these are handled by easydel huggingface transformers in easydel onlu being used for download model weights nothing more and less and for generation pipeline (static method) and same as PyTorch that only being used for data loaders 

In case of handling partition specs those are things that you should handle that, in some parts i can say.

Overall EasyDel is both low and high level library it's up to you how much of the easydel potential you want to get

**Comment by erfanzar** [comment]
Ill soon create an example for you

**Comment by erfanzar** [comment]
ill be happy to do that also but there are a lot of things that I have to implement like ring attention for GPUs, SFTTrainer and ...

and here's the partition rules that you have to use

```python
rule = (
            ("model/embed_tokens/embedding", PartitionSpec("tp", ("fsdp", "sp"))),

            ("self_attn/(q_proj|k_proj|v_proj)/kernel", PartitionSpec(("fsdp", "sp"), "tp")),
            ("self_attn/o_proj/kernel", PartitionSpec("tp", ("fsdp", "sp"))),

            ("mlp/gate_proj/kernel", PartitionSpec(("fsdp", "sp"), "tp")),
            ("mlp/down_proj/kernel", PartitionSpec("tp", ("fsdp", "sp"))),
            ("mlp/up_proj/kernel", PartitionSpec(("fsdp", "sp"), "tp")),

            ("input_layernorm/kernel", PartitionSpec(None)),
            ("post_attention_layernorm/kernel", PartitionSpec(None)),

            ("model/norm/kernel", PartitionSpec(None)),
            ("lm_head/kernel", PartitionSpec(("fsdp", "sp"), "tp")),
            (".*", PartitionSpec(None)),
)

config.get_partition_rules = lambda _:rule # this will set model config partition to the given custom partition rule
```
