### ISSUE TITLE
Received an error while using pipeline generation using llama model

### ISSUE THREAD

**Issue by rakesh010101** [erfanzar/EasyDeL#174]
**Describe the bug**

Received an error while using pipeline generation using  llama model

```
ARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1730811298.827353 3480725 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1730811298.832223 3480725 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
Converting Model: 100%|██████████████████████████████████████████████████████████████████████| 147/147 [00:52<00:00,  2.79it/s]
2024-11-05 12:56:02,125 INFO     [easydel.inference.generation_pipeline.pipeline] compiling `model_kwargs_sharding`.
2024-11-05 12:57:09,006 INFO     [easydel.inference.generation_pipeline.pipeline] compiling `perform_sampling_step`.
Traceback (most recent call last):
  File "/home/app/EasyDeL/3.py", line 66, in <module>
    response = pipeline.generate(messages)
  File "/home/app/EasyDeL/easydel/inference/generation_pipeline/pipeline.py", line 768, in generate
    for sequence in self.pipeline.generate(echo=True, **inputs):
  File "/home/app/EasyDeL/easydel/inference/generation_pipeline/pipeline.py", line 325, in generate
    generation_state = self.get_or_compile_sampling_function(
  File "/home/app/EasyDeL/easydel/inference/generation_pipeline/pipeline.py", line 559, in get_or_compile_sampling_function
    self.compile_sampling_function(
  File "/home/app/EasyDeL/easydel/inference/generation_pipeline/pipeline.py", line 436, in compile_sampling_function
    def shard_generation_state(st):
  File "/home/app/.cache/pypoetry/virtualenvs/easydel-9QYVTRJ_-py3.10/lib/python3.10/site-packages/jax/_src/api.py", line 280, in jit
    return pjit.make_jit(
  File "/home/app/.cache/pypoetry/virtualenvs/easydel-9QYVTRJ_-py3.10/lib/python3.10/site-packages/jax/_src/pjit.py", line 520, in make_jit
    jit_info = _parse_jit_arguments(
  File "/home/app/.cache/pypoetry/virtualenvs/easydel-9QYVTRJ_-py3.10/lib/python3.10/site-packages/jax/_src/pjit.py", line 439, in _parse_jit_arguments
    in_shardings = prepare_axis_resources(in_shardings, 'in_shardings')
  File "/home/app/.cache/pypoetry/virtualenvs/easydel-9QYVTRJ_-py3.10/lib/python3.10/site-packages/jax/_src/sharding_impls.py", line 1132, in prepare_axis_resources
    new_entries.append(ParsedPartitionSpec.from_user_input(
  File "/home/app/.cache/pypoetry/virtualenvs/easydel-9QYVTRJ_-py3.10/lib/python3.10/site-packages/jax/_src/sharding_impls.py", line 1066, in from_user_input
    raise TypeError(f"{arg_name} are expected to be "
TypeError: in_shardings leaf specifications are expected to be PartitionSpec instances or None, but got -inf

```

**To Reproduce**

Example Code run using main branch
```
# Import necessary modules
import easydel as ed
from transformers import AutoTokenizer
import jax
from jax import numpy as jnp, lax

# Model configuration
model_name = "meta-llama/Llama-3.2-1B-Instruct"
max_length = 4096
dtype = jnp.float16
sharding_axis_dims = (1, 1, 1, -1)
num_devices = len(jax.devices())
input_shape = (num_devices, max_length)
partition_axis = ed.PartitionAxis()

# Load and configure model with EasyDeL
model, params = ed.AutoEasyDeLModelForCausalLM.from_pretrained(
    model_name,
    input_shape=input_shape,
    auto_shard_params=True,
    sharding_axis_dims=sharding_axis_dims,
    config_kwargs={
        "use_scan_mlp": False,
        "partition_axis": partition_axis,
        "attn_dtype": dtype,
        "freq_max_position_embeddings": max_length,
        "mask_max_position_embeddings": max_length,
        "attn_mechanism": ed.AttentionMechanisms.FLASH_ATTN2,
    },
    #quantization_method="8bit",
    platform="jax",
    param_dtype=dtype,
    dtype=dtype,
    precision=lax.Precision("fastest"),
)

# Initialize the tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.padding_side = "left"
tokenizer.pad_token_id = tokenizer.eos_token_id

# Create the Generation Pipeline with specific parameters
pipeline = ed.ChatPipeline(
    pipeline=ed.GenerationPipeline(
        model=model,
        params=params,
        tokenizer=tokenizer,
        generation_config=ed.GenerationPipelineConfig(
            max_new_tokens=1024,
            temperature=model.generation_config.temperature,
            top_p=model.generation_config.top_p,
            top_k=model.generation_config.top_k,
            eos_token_id=model.generation_config.eos_token_id,
        ),
    ),
    max_prefill_length=2048,
)

# Define chat messages
messages = [
    {"role": "system", "content": "You are a pirate chatbot who always responds in pirate speak!"},
    {"role": "user", "content": "Who are you?"},
]

# Generate and print the response
response = pipeline.generate(messages)
print(response)



```

**Comment by erfanzar** [comment]
Hi, Actually im about to remove gen pipeline and connect chat pipeline to vinference since thats way faster 
(I don't recommend using flash attn 2 with jax platform since that's way slower (its more memory efficient btw))
