### ISSUE TITLE
The function call llama_from_pretrained expects a device param that is missing while call it

### ISSUE THREAD

**Issue by jchauhan** [erfanzar/EasyDeL#75]
**Describe the bug**
It seems the code is broken as the at main branch and also at tag 0.0.42. The function call llama_from_pretrained expects a device param that is missing while call it

**To Reproduce**
1. checkout the latest code
2. Instal and setup 
3. Run it 
```
python -m examples.serving.causal-lm.llama-2-chat   --pretrained_model_name_or_path="mediocredev/open-llama-3b-v2-chat" --max_length=4096   --max_new_tokens=2048 --max_compile_tokens=32 --temperature=0.6   --top_p=0.95 --top_k=50   --dtype="fp32" --use_prefix_tokenizer
Traceback (most recent call last):
  File "/home/**/.pyenv/versions/3.10.0/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/neo/.pyenv/versions/3.10.0/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/***/research/EasyDeL/examples/serving/causal-lm/llama-2-chat.py", line 193, in <module>
    server = Llama2Host.load_from_torch(
  File "/home/***/research/EasyDeL/examples/serving/causal-lm/llama-2-chat.py", line 53, in load_from_torch
    param, config_model = llama_from_pretrained(
TypeError: llama_from_pretrained() missing 1 required positional argument: 'device'

```

**Comment by erfanzar** [comment]
Examples are out dated ill try to fix them as soon as possible (next commit)

**Comment by erfanzar** [comment]
when using transform funcs like `llama_from_pretrained` they except a device to offload the weights on you can pass that

```python
device = jax.devices("cpu")[0]
```
