### ISSUE TITLE
Error running remote model that has custom code

### ISSUE THREAD

**Issue by jchauhan** [erfanzar/EasyDeL#94]
```
ValueError: Loading this model requires you to execute custom code contained in the model repository on your local machine. Please set the option `trust_remote_code=True` to permit loading of this model.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xxx/research/transformers/train_phi2_easydel.py", line 21, in <module>
    model, params = AutoEasyDelModelForCausalLM.from_pretrained(huggingface_repo_id_or_path, trust_remote_code=True)
  File "/home/xxx/research/EasyDeL/lib/python/EasyDel/modules/auto_easydel_model.py", line 221, in from_pretrained
    config = AutoConfig.from_pretrained(pretrained_model_name_or_path)
  File "/home/xxx/research/EasyDeL/.venv/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1085, in from_pretrained
    trust_remote_code = resolve_trust_remote_code(
  File "/home/xxx/research/EasyDeL/.venv/lib/python3.10/site-packages/transformers/dynamic_module_utils.py", line 611, in resolve_trust_remote_code
    raise ValueError(
ValueError: The repository for stabilityai/stable-code-3b contains custom code which must be executed to correctly load the model. You can inspect the repository content at https://hf.co/stabilityai/stable-code-3b.


```

**Comment by erfanzar** [comment]
the model don't have a hugging face implementation so it  also have no EasyDeL implementation too

**Comment by erfanzar** [comment]
this issue is being closed due to no response has been given
